//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Пространство имен Sys.Services.Drv
namespace Ztp.Port.TcpPort
{
  /// <summary/>
  public partial class TcpPortSettings : IPortSetting
  {
    private int _timeout = 10000;
    public int Timeout
    {
      get
      {
        return _timeout;
      }
      set
      {
        _timeout = value;
      }
    }
    public PortKind Kind
    {
      get
      {
        return PortKind.Tcp;
      }
      set { }
    }

    /// <summary>
    /// Поле для свойства Хост
    /// </summary>
    private string _ipAddress = "127.0.0.1";

    /// <summary>
    /// Поле для свойства Порт
    /// </summary>
    private uint _port = 10000;

    /// <summary>
    /// Интернал конструктор
    /// </summary>
    internal TcpPortSettings(string ipAddress, uint port)
    {
      this.IpAddress = ipAddress;
      this.Port = port;
    }

    /// <summary>
    /// Публичный конструктор
    /// </summary>
    public TcpPortSettings()
    {
    }

    /// <summary>
    /// Свойство Хост
    /// </summary>
    public virtual string IpAddress
    {
      get
      {
        return _ipAddress;
      }
      set
      {
        this._ipAddress = value;
      }
    }

    /// <summary>
    /// Свойство Порт
    /// </summary>
    public virtual uint Port
    {
      get
      {
        return _port;
      }
      set
      {
        this._port = value;
      }
    }

    public string ToDisplay()
    {
      return $"{IpAddress}:{Port}";
    }

  }
}
